### ISSUE TITLE
Review 13/12

### ISSUE THREAD

**Issue by JanUrbanHtw** [JanUrbanHtw/LeafAlone#23]
- [ ] change error messages color to red
- [ ] Contributor application via Email #18 
- [ ] change "Submit for Review" in the addPlantCare
- [ ] Better units for WaterAmount
- [ ] Outsource registration to service LeafAloneUserDetailsService #21 
- [ ] use @Valid to remove logic from PlantsController (catch thrown errors and add Binding errors accordingly)
- [ ] Introduce ViewModels 
- [ ] Plant Schedule Page (Bootstrap cards?)
- [ ] move plantname problem to Service  #21 #19
